### ISSUE TITLE
想请教作者关于文件夹复制的问题

### ISSUE THREAD

**Issue by DDusky** [hunterhug/fafacms#6]
在思否上看到作者的类似问题，想请教一下基于mysql存储的文件夹复制的问题
[问题链接](https://segmentfault.com/q/1010000020838859)
目前想不出可以避免大量递归 select 的实现方法，所以请教一下，感激不尽！
@hunterhug

**Comment by hunterhug** [comment]
> 在思否上看到作者的类似问题，想请教一下基于mysql存储的文件夹复制的问题
> [问题链接](https://segmentfault.com/q/1010000020838859)
> 目前想不出可以避免大量递归 select 的实现方法，所以请教一下，感激不尽！
> @hunterhug

使用递归进行select放入内存后进行处理后，再批量插入，这样实现的复制文件夹。

**Comment by DDusky** [comment]
> > 在思否上看到作者的类似问题，想请教一下基于mysql存储的文件夹复制的问题
> > [问题链接](https://segmentfault.com/q/1010000020838859)
> > 目前想不出可以避免大量递归 select 的实现方法，所以请教一下，感激不尽！
> > @hunterhug
> 
> 使用递归进行select放入内存后进行处理后，再批量插入，这样实现的复制文件夹。

谢谢，目前实现方法一致
